[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

upload_port = COM6
monitor_port = COM6
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21.5
    https://github.com/mandulaj/PZEM-004T-v30.git#v1.2.1

build_flags =
    -DCORE_DEBUG_LEVEL=0